spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/6dd267b6-3931-4cb1-8998-0daef7059841/
          jwk-set-uri: https://login.microsoftonline.com/6dd267b6-3931-4cb1-8998-0daef7059841/discovery/keys